/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.LoginDAO;
import POJO.KhachHang;
import POJO.NhanVien;
import SP.Mes;
import java.time.LocalDate;

/**
 *
 * @author HP
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    // Các biến cần lưu đầu tiên 
    // 
    NhanVien nv = null;

    
    public DangNhap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        icon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        key = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        btnDangNhap = new javax.swing.JButton();
        txtMatKhau = new javax.swing.JPasswordField();
        cbo_Quyen = new javax.swing.JComboBox<>();
        background = new javax.swing.JLabel();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng Nhập");
        setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES/open-book.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("...");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 30, -1));

        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES/user.png"))); // NOI18N
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        key.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES/key.png"))); // NOI18N
        getContentPane().add(key, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 50, -1));

        txtTenDangNhap.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTenDangNhap.setText("nhanvien2");
        txtTenDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(txtTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 160, 30));

        btnDangNhap.setBackground(new java.awt.Color(0, 153, 153));
        btnDangNhap.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        txtMatKhau.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMatKhau.setText("123");
        getContentPane().add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 177, 160, 30));

        cbo_Quyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bán Hàng", "Quản Lý", "Kho" }));
        getContentPane().add(cbo_Quyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 130, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES/background.png"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(1550, 1098));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        String tileTB = "Thông báo nhập!";
        if (Mes.boolJTextField(txtTenDangNhap) == true) {
            Mes.ThongBao(tileTB, "Chưa nhập tên Đăng Nhập");
            return;
        }

        if (Mes.boolJTextField(txtMatKhau) == true) {
            Mes.ThongBao(tileTB, "Bạn chư nhập Mật Khẩu");
            return;
        }

        String ql = (String) cbo_Quyen.getSelectedItem();
        int quyen = 0;
        if (ql.equalsIgnoreCase("Quản lý")) {
            quyen = 1;
        }
        if (ql.equalsIgnoreCase("Bán hàng")) {
            quyen = 2;
        }
        if (ql.equalsIgnoreCase("Kho")) {
            quyen = 3;
        }
        if (quyen == 0) {
            Mes.ThongBao(tileTB, "Bạn cần chọn quyền của Tài khoản!");
        }
        LoginDAO dn = new LoginDAO();
        nv =dn.getEmployeeByUsernameAndPassword(txtTenDangNhap.getText(), txtMatKhau.getText(),quyen);
        if(nv != null)
        {
                Mes.ThongBao("Đăng nhập thành công", "Xin chào " + nv.getTenNV() + "\n Nhân viên:" + ql);
                if(quyen == 1){
                    Mes.OpenFrom(new TrangChuAdmin(nv));
                    this.dispose();
                }
                 if(quyen == 2){
                    fTrangChuNhanVienBanHang banhang = new fTrangChuNhanVienBanHang(nv);
                    banhang.setVisible(true);
                    //ds.setLocationRelativeTo(ds);
                    this.dispose();
                }
                  if(quyen == 3){
                    TrangChuNhanVienKho kho = new TrangChuNhanVienKho();
                    kho.setVisible(true);
                    //ds.setLocationRelativeTo(ds);
                    this.dispose();
                }
              
        }
        else 
        {
            Mes.ThongBao("Đăng nhập", "Không thành công!");
        }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void txtTenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDangNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JComboBox<String> cbo_Quyen;
    private javax.swing.JLabel icon;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel key;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
